import type { Metadata } from "next";
import "./globals.css";
import { ApolloClientProvider } from "@/utils";
import { Layout } from "@/components/ui/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloClientProvider>
          <Layout>{children}</Layout>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
